# Clippy configuration for Gren LSP
# This file configures clippy lints to enforce project coding standards

# Disallow specific crates that we want to avoid
disallowed-methods = [
    # Regex crate functions - use tree-sitter parsing instead
    { path = "regex::Regex::new", reason = "Use tree-sitter parsing instead of regex for accurate syntax analysis" },
    { path = "regex::Regex::is_match", reason = "Use tree-sitter parsing instead of regex for accurate syntax analysis" },
    { path = "regex::Regex::find", reason = "Use tree-sitter parsing instead of regex for accurate syntax analysis" },
    { path = "regex::Regex::find_iter", reason = "Use tree-sitter parsing instead of regex for accurate syntax analysis" },
    { path = "regex::Regex::captures", reason = "Use tree-sitter parsing instead of regex for accurate syntax analysis" },
    { path = "regex::Regex::captures_iter", reason = "Use tree-sitter parsing instead of regex for accurate syntax analysis" },
    { path = "regex::Regex::split", reason = "Use tree-sitter parsing instead of regex for accurate syntax analysis" },
    { path = "regex::Regex::replace", reason = "Use tree-sitter parsing instead of regex for accurate syntax analysis" },
    { path = "regex::Regex::replace_all", reason = "Use tree-sitter parsing instead of regex for accurate syntax analysis" },
]

disallowed-types = [
    # Regex types - use tree-sitter parsing instead
    { path = "regex::Regex", reason = "Use tree-sitter parsing instead of regex for accurate syntax analysis" },
    { path = "regex::RegexBuilder", reason = "Use tree-sitter parsing instead of regex for accurate syntax analysis" },
    { path = "regex::Match", reason = "Use tree-sitter parsing instead of regex for accurate syntax analysis" },
    { path = "regex::Captures", reason = "Use tree-sitter parsing instead of regex for accurate syntax analysis" },
]

# Allow certain regex usage only in very specific cases (like URL encoding)
# These would need to be explicitly allowed with #[allow(clippy::disallowed_types)]
allow-mixed-uninlined-format-args = false